import json
import os
import pandas as pd
from sqlalchemy import create_engine
import datetime

def load_json_to_postgres(file_path, db_path):
    """
    Loads a JSON file generated by the scraper into the SQLite raw database.
    """
    if not os.path.exists(file_path):
        print(f"File {file_path} not found. Skipping.")
        return

    with open(file_path, 'r') as f:
        data = json.load(f)

    results = data.get('results', [])
    if not results:
        print("No results found in JSON. Skipping.")
        return

    df = pd.DataFrame(results)

    # Standardize column names to snake_case
    column_mapping = {
        'placeId': 'place_id',
        'name': 'business_name',
        'address': 'full_address',
        'phone': 'phone_number',
        'hasWebsite': 'has_website',
        'isActive': 'is_active',
        'emails': 'emails'
    }
    df = df.rename(columns=column_mapping)

    # Add metadata
    df['scraped_at'] = data.get('scrapedAt', datetime.datetime.now().isoformat())
    df['search_query'] = data.get('query', '')
    df['search_location'] = data.get('location', '')
    df['batch_id'] = datetime.datetime.now().strftime('%Y%m%d%H%M%S')

    # Convert complex objects to strings for raw storage
    for col in df.columns:
        if df[col].apply(lambda x: isinstance(x, (list, dict))).any():
            df[col] = df[col].apply(lambda x: json.dumps(x) if isinstance(x, (list, dict)) else x)

    # SQLite connection (raw.db)
    engine = create_engine(f'sqlite:///{db_path}')
    df.to_sql('google_maps_places', engine, if_exists='append', index=False)
    print(f"Successfully loaded {len(df)} rows to {db_path} table google_maps_places")

if __name__ == "__main__":
    # For local testing
    # Get date for the default filename
    date_str = datetime.datetime.now().strftime('%Y-%m-%d')
    default_file = f"data/results_{date_str}.json"
    
    DB_PATH = os.getenv('DB_PATH', '/home/jvv/info-getter/sqlite/raw.db')
    DATA_FILE = os.getenv('DATA_FILE', default_file)
    
    print(f"Loading from {DATA_FILE} to {DB_PATH}")
    load_json_to_postgres(DATA_FILE, DB_PATH)
